# Generated by Django 4.2.7 on 2023-11-13 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='InstituteSpeciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infrastucture.institute')),
                ('speciality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infrastucture.speciality')),
            ],
        ),
        migrations.CreateModel(
            name='InstituteProfession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infrastucture.institute')),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infrastucture.profession')),
            ],
        ),
        migrations.AddField(
            model_name='institute',
            name='professions',
            field=models.ManyToManyField(through='infrastucture.InstituteProfession', to='infrastucture.profession'),
        ),
        migrations.AddField(
            model_name='institute',
            name='specialities',
            field=models.ManyToManyField(through='infrastucture.InstituteSpeciality', to='infrastucture.speciality'),
        ),
    ]
